#!/bin/bash
export TERM=screen-256color
source ~/.fzf.bash
source /opt/ros/melodic/setup.bash

# Suppress GTK accessibility known bug with this env var
export NO_AT_BRIDGE=1

# DIR PATHS
export DROPBOX="$HOME/Dropbox"
export PROJECTS="$HOME/projects"
export DOTFILES="$HOME/dotfiles"

# DIR SHORTCUTS
alias downloads="cd $HOME/Downloads";
alias dotfiles="cd $DOTFILES";
alias scripts="cd $HOME/dotfiles/scripts"
alias catkin_ws="cd ~/catkin_ws/"
alias notes="cd $PROJECTS/chutsu.github.io/docs/notes; vim; cd -"

# Projects
alias autocal="cd $PROJECTS/autocal"
alias yac="cd $PROJECTS/yac"
alias alpha="cd $PROJECTS/alpha"
alias proto="cd $PROJECTS/proto"
alias proto_ros="cd $PROJECTS/proto_ros"
alias poct="cd $PROJECTS/proto/octave"
alias parts="cd $PROJECTS/parts"
alias play="cd $PROJECTS/play"
alias ditto="cd $PROJECTS/ditto"
alias papers="cd $PROJECTS/papers"
alias zp3="cd $PROJECTS/zp3"
alias zero="cd $PROJECTS/zero"
alias red="cd $PROJECTS/red"
alias sr="cd $PROJECTS/sr"
alias phd="cd $PROJECTS/phd"
alias chutsu="cd $PROJECTS/chutsu.github.io"
alias rs4se="cd $PROJECTS/rs4se"
alias bag2se="cd $PROJECTS/bag2se"

# GIT ALIASES
alias gitlog="git log --graph \
    --abbrev-commit \
    --decorate \
    --date=relative \
    --format=format:'%C(bold blue)%h%C(reset) \
    - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' \
    --all"

# EXECUTIONAL SHORTCUTS
alias ls='ls -lh --group-directories-first --color'
alias la='ls -lha --color'
alias search='apt-cache search'
alias install='sudo apt-get install'
alias update='sudo apt-get update'
alias remove='sudo apt-get remove'
alias purge='sudo apt-get purge'
alias vimrc="cd $HOME/dotfiles && vim vim/vimrc && cd -";
alias bashrc="cd $HOME && vim .bash_profile && cd - && source ~/.bash_profile";
alias todo="vim $HOME/projects/TODO; cd -";
alias tasks="grep --exclude-dir=.git -rEI 'TODO|FIXME' . 2>/dev/null";
alias search="grep -nr $1 ."
alias headphones="pulseaudio --start; sleep 5; \
                  echo -e 'connect 74:45:CE:0B:42:F9' | bluetoothctl ; sleep 5; \
                  pacmd set-card-profile bluez_card.74_45_CE_0B_42_F9 a2dp_sink"

# ENVIRONMENTAL SETTINGS
export PATH=$PATH:~/dotfiles/scripts
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export VISUAL=vim
export EDITOR=vim

# FZF Settings
# -- Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
# -- Apply the command to CTRL-T as well
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# SHELL SETTINGS
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
PS1='[\w]\[\033[1;35m\]$(parse_git_branch)\[\033[0m\] > '
export HISTSIZE=1000000
export HISTFILESIZE=1000000000
if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi
[[ $- == *i* ]] && stty -ixon  # disable ctrl-s (software flow control)

# START TMUX ON BASH STARTUP
# if which tmux >/dev/null 2>&1; then  # check if tmux is installed
#   if tmux ls >/dev/null 2>&1; then  # check if tmux already has sessions
#     [[ -z "$TMUX" ]] && exec tmux attach
#   else
#     [[ -z "$TMUX" ]] && exec tmux -2 -f ~/.tmux.conf
#   fi
# fi
