#!/bin/bash
export TERM=screen-256color
if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash
fi
if [ -f /opt/ros/noetic/setup.bash ]; then
  source /opt/ros/noetic/setup.bash
fi

# ENVIRONMENTAL SETTINGS
export PATH=$PATH:~/dotfiles/scripts:~/.local/bin:/usr/local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export VISUAL=nvim
export EDITOR=nvim

# SHELL HISTORY
shopt -s histappend
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

# DIR PATHS
export DROPBOX="$HOME/Dropbox"
export PROJECTS="$HOME/projects"
export DOTFILES="$HOME/dotfiles"

# DIR SHORTCUTS
alias down="cd $HOME/Downloads";
alias dotfiles="cd $DOTFILES";
alias scripts="cd $HOME/dotfiles/scripts"
alias catkin_ws="cd ~/catkin_ws/"
alias yac="cd $PROJECTS/yac"
alias proto="cd $PROJECTS/proto/proto"
alias proto_ros="cd $PROJECTS/proto_ros"
alias proto_mav="cd $PROJECTS/proto_mav"
alias papers="cd $PROJECTS/papers"
alias phd="cd $PROJECTS/phd"
alias chutsu="cd $PROJECTS/chutsu.github.io"

sync_projects() {
  mkdir -p "$HOME/projects";
  cd "$HOME/projects" || return;
  declare -a PROJECTS=(
    "yac"
    "proto"
    "papers"
    "phd"
    "chutsu.github.io"
  )

  for PROJ in "${PROJECTS[@]}"; do
    if [ ! -d "$HOME/projects/$PROJ" ]; then
      cd "$HOME/projects";
      git clone "git@github.com:chutsu/$PROJ"
    fi

    cd "$HOME/projects/$PROJ";
    git pull
  done
}
alias sync_proj="sync_projects"

# EXECUTIONAL SHORTCUTS
lock() {
  i3lock -c 000000
  xset dpms force off
}

alias vim='nvim'
alias ls='ls -lh --group-directories-first --color'
alias la='ls -lha --color'
alias vimrc="cd $HOME/dotfiles && vim vim/vimrc && cd -";
alias bashrc="cd $HOME && vim .bash_profile && cd - && source ~/.bash_profile";
alias todo="vim $HOME/projects/TODO; cd -";
alias tasks="grep --exclude-dir=.git -rEI 'TODO|FIXME' . 2>/dev/null";
alias search="grep -nr $1 ."
alias brightness_max="echo 100 | sudo tee /sys/class/backlight/nv_backlight/brightness"

# SHELL SETTINGS
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
PS1='[\h:\w]\[\033[1;35m\]$(parse_git_branch)\[\033[0m\] > '
export HISTSIZE=1000000
export HISTFILESIZE=1000000000
if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi
[[ $- == *i* ]] && stty -ixon  # disable ctrl-s (software flow control)
