#!/bin/sh

# Start dbus
if [ -z "${DBUS_SESSION_BUS_ADDRESS-}" ] && type dbus-launch >/dev/null; then
  eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# Start i3
xbindkeys
exec i3
fbsetroot -solid grey30
