#!/bin/sh

# start dbus
if [ -z "${DBUS_SESSION_BUS_ADDRESS-}" ] && type dbus-launch >/dev/null; then
  eval $(dbus-launch --sh-syntax --exit-with-session)
fi 

xbindkeys
exec i3
# exec startxfce4
fbsetroot -solid grey30
