#!/bin/bash
# This script replacs underscores "_" with a space char instead
#
# author: Chris Choi <chutsu@gmail.com>

progname=`basename $0`

if [ $# != 1 ]
then 
	echo "Script replaces \"_\" and adds a space \" \" instead"
	echo "Usage: $progname \"target file\""
	exit 1
fi

old_name=$1
dir=`dirname "$1"`
file=`basename "$1"`

new_file=`echo $file | sed "s/_/ /g"`
new_name=$dir"/"$new_file

if [ "$old_name" != "$new_name" ]
then
        mv "$old_name" "$new_name"
fi

exit 0

