#!/bin/sh
set -e

function cleanup {
    echo "removing expanded package!"
    rm -rf ${1/.tar.gz/}
}


trap cleanup EXIT
echo "Installing $1"
tar -xzvf $1
cd ${1/.tar.gz/}
makepkg
sudo pacman --noconfirm -U `ls | grep x86_64.pkg.tar.xz`
cd ..
rm -rf ${1/.tar.gz/}
mv $1 pkg
