#!/bin/sh -e
session='sandbox'
tmux new-session -d -s $session

# Window0 - nvim
tmux rename-window -t $session:0 'nvim'
# tmux send-keys -t $session:0 'nvim' C-m

# Window1 - dev
tmux new-window -t $session:1 -n 'dev'

# Window2 - vifm
tmux new-window -t $session:2 -n 'vifm'
tmux send-keys -t $session:2 'vifm' C-m

# Attach to session
tmux attach-session -t $session:0
