#!/usr/bin/env python
# A script to see if a particular process is currently running
#
# author: Chris Choi <chutsu@gmail.com>
import os
import sys

# settings
home_dir = os.path.expanduser("~")
if sys.argv.__len__() == 1:  # parse command-line args
    print "ERROR! what is the process name?"
    sys.exit(-1)
process = sys.argv[1]

# query system for process
os.system("ps -ef | grep {0} > {1}/tmp.out".format(process, home_dir))
output = open("{0}/tmp.out".format(home_dir), "rb").read().split("\n")
os.remove("{0}/tmp.out".format(home_dir))

# output results
if output.__len__() == 4:
    print "process [{0}] not running".format(process)
else:
    for lines in output[:-3]:
        print lines
