#!/bin/bash
# Converts mkv to avi
# Note: Mencoder needs to be installed
# author: Chris Choi <chutsu@gmail.com>

if [ $# != 1 ]
	then
		echo "Usage: $progname movie.mkv converted_movie.avi"
		echo "This script converts mkv to avi."
		echo
	exit 1
fi

mencoder $1 -oac mp3lame -ovc copy -o "${1/.mkv/.avi}"

