#!/bin/sh

MESSAGE=$(cat)

# get from, email and sender details
FROM=$(echo "${MESSAGE}" | grep ^"From: ")
EMAIL=$(echo ${FROM} | cut -d "<" -f2 | cut -d ">" -f1)
SENDER=$(echo ${FROM} | cut -c6- | cut -f1 -d '<' | sed 's/"//g')

# check if sender has comma
echo $SENDER | grep -F ',' > /dev/null
NO_COMMA=$?

if [ $NO_COMMA -eq 0 ]; then
    # remove comma and get first and last name in right order
    FIRSTNAME=$(echo $SENDER | cut -d ',' -f2)
    LASTNAME=$(echo $SENDER | cut -d ',' -f1)
    SENDER="$FIRSTNAME $LASTNAME"
fi

# build alias string
ALIAS=$(echo ${SENDER} | tr '[:upper:]' '[:lower:]' | sed 's/\ /_/g')
grep -Fxq "alias ${ALIAS} ${SENDER} ${EMAIL}" $HOME/.mutt/aliases.txt
UNIQUE=$(echo $?)

if [ "$UNIQUE" -eq 1 ]; then
    echo "alias $ALIAS $SENDER $EMAIL" >> $HOME/.mutt/aliases.txt
fi

# echo rest of the message
echo "${MESSAGE}"
