#!/usr/bin/env python3
import psutil

disp = []
disp.append(f"CPU: {psutil.cpu_percent(0.5)}%")
disp.append(f"MEM: {psutil.virtual_memory().percent}%")

battery = psutil.sensors_battery()
if battery and battery.power_plugged:
    disp.append(f"PWR [CHR]: {battery.percent:.1f}%")
else:
    disp.append(f"PWR [DIS]: {battery.percent:.1f}%")

print(" | ".join(disp) + " ")
