#!/usr/bin/env python3
import psutil

memory = psutil.virtual_memory()
battery = psutil.sensors_battery()

cpu_usage = psutil.cpu_percent(0.5)
mem_usage = memory.percent
pwr_usage = battery.percent

print(f"CPU: {cpu_usage}% | RAM: {mem_usage:.1f}% | PWR: {pwr_usage:.1f}%")
