#!/bin/bash
set -e

INPUT_PATH=$1

FNAME=$(basename -- "$INPUT_PATH")
FEXT="${FNAME##*.}"
FNAME="${FNAME%.*}"

#ffmpeg -i $INPUT_PATH -vf "fps=10,scale=1024:-1:flags=lanczos" -c:v gif ${INPUT_PATH/FEXT/}.gif

ffmpeg -i $INPUT_PATH -vf "fps=15,scale=1024:-1:flags=lanczos,palettegen" palette.png
ffmpeg -i $INPUT_PATH -i palette.png -filter_complex "fps=15,scale=1024:-1:flags=lanczos[x];[x][1:v]paletteuse" -c:v gif ${INPUT_PATH/.mp4/}.gif

