#!/bin/bash
# This script helps you rename a whole season of videos in one go
#
# author: Chris Choi <chutsu@gmail.com>

set -e

echo "This script is designed to rename a whole season of videos in one go!"
ls -lh
echo "What extension do the videos have?(ignoring the dot)"
read extension
echo "What season are the videos?"
read ans
echo
echo "You are about to rename the files to:"

if [ "$ans" -lt 10 ]; then season="0""$ans"; else season="$ans"; fi

# list the videos and what they will be renamed to
epiNum=0
for i in *."$extension"; do
	let epiNum=epiNum+1
	if [ "$epiNum" -lt 10 ]; then
		echo "$i" " --> " "S$season""E0$epiNum"" - .$extension"
	else
	 	echo "$i" " --> " "S$season""E$epiNum"" - .$extension"
	fi
done

# Asks for confirmation for renaming
loop=1
while [ $loop ]; do
	echo "Are you sure?(y/n)"
	read ans2

	if [ $ans2 = 'y' ]; then
		epiNum=0
		for i in *."$extension"; do
			let epiNum=epiNum+1
			if [ "$epiNum" -lt 10 ]; then
				mv "$i" "S$season""E0$epiNum"" - .$extension"
			else
			 	mv "$i" "S$season""E$epiNum"" - .$extension"
			fi
		done
		exit
	elif [ $ans2 != 'n' ]; then
		echo "Please enter either y or n !"
	else
		echo "Exiting.."
		exit
	fi
done



