#!/bin/bash
VOLUME=$(amixer get Master | egrep -m 1 -o "[0-9]+%")
MUTED=$(amixer get Master | egrep -m 1 -o "off")
RESULT=$VOLUME

# is volume muted?
if [ "$MUTED" == "off" ]; then
    RESULT="$RESULT [muted]";
fi

echo $RESULT
