name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build Docker image (make deps, dotfiles, install_neovim)
      run: docker build -t dotfiles-test .
